### ISSUE TITLE
Problem running on W11

### ISSUE THREAD

**Issue by spectrumcomputing** [stevehjohn/Zen#19]
Hi Stevo,

It's Peter from the Spectrum Computing website.

I'm trying to test Zen ([v1.0.1](https://github.com/stevehjohn/Zen/releases/tag/v1.0.1)) on W11 (Microsoft Windows [Version 10.0.22621.2428]), but get this error in the exceptions.log file when I double click 'Zen.Desktop.Host.exe':

It looks like it's trying to find directory C:\ROM Images\ ?

Please let me know if you need more information.

```
--------------------------------------------------------------------------------
Time: 2023-10-31 12:37:25Z
Component: Program
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Rom Images\ZX Spectrum +2\image-0.rom'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at Zen.System.Motherboard.LoadRom(Int32 romNumber) in C:\Git\Zen\src\Zen.System\Motherboard.cs:line 340
   at Zen.System.Motherboard..ctor(Model model) in C:\Git\Zen\src\Zen.System\Motherboard.cs:line 95
   at Zen.Desktop.Host.Infrastructure.Host.SetMotherboard(Model model) in C:\Git\Zen\src\Zen.Desktop.Host\Infrastructure\Host.cs:line 90
   at Zen.Desktop.Host.Program.Main() in C:\Git\Zen\src\Zen.Desktop.Host\Program.cs:line 12
```

The first time I ran the program I was asked to download '.NET 7.0 Desktop Runtime (v7.0.13) - Windows x64 Installer'.  I did this, and rebooted.

This is my PC specification:

```
Device name	DESKTOP-JJM4VS0
Processor	AMD Ryzen 7 2700X Eight-Core Processor            3.70 GHz
Installed RAM	32.0 GB
Device ID	CE2C99F9-F3D2-41EA-838F-AD0291E7E679
Product ID	00330-80000-00000-AA924
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```

**Comment by stevehjohn** [comment]
Hi Peter,

Did you unzip the files to `C:\`?

Thanks,

Steve.

**Comment by stevehjohn** [comment]
Hi Peter,

I've created a new release. Looks like I didn't include the ROM images previously. Thanks for bringing this to my attention.

Steve.

**Comment by spectrumcomputing** [comment]
Hi Steve,

I had not previously (did I miss this in the notes?), however I just unzipped to the root and no difference. Is the root of the C drive the only place it can go?

I tried it so everything is in c:\Zen.Desktop.Host.Windows, and also everything is in c:\

There is no ROM Images folder in the release. either.  Am I missing a step?

Thanks

**Comment by stevehjohn** [comment]
Hi Peter,

No, it should work anywhere you want to unzip it. It looks like I stupidly didn't put the ROM images in the previous release - my bad. The latest one should work.

Thanks,

Steve.

**Comment by spectrumcomputing** [comment]
Excellent, thanks Steve,

I will post a feature about the new emulator on the forums.

Thanks for fixing so quick.

**Comment by stevehjohn** [comment]
That's very kind Peter. Can you confirm it works for you now?

Thanks,

Steve.

**Comment by spectrumcomputing** [comment]
Yes, all working.  Cheers

**Comment by stevehjohn** [comment]
Great. Thanks for confirming. Would you mind posting a link to the post when you have done it please?

Thanks again,

Steve.

**Comment by spectrumcomputing** [comment]
Hi, 

Added here.  Let me know if I missed anything.

https://spectrumcomputing.co.uk/forums/viewtopic.php?t=10383

**Comment by stevehjohn** [comment]
Awesome, thanks.

If you don't mind, could you mention its USP, the waveform visualliser? Sorry to be a pain.

Steve.

**Comment by spectrumcomputing** [comment]
You certainly are not a pain!  Comments added. Thanks for joining the forum!

**Comment by stevehjohn** [comment]
Thank you for updating the post. A pleasure to be a member of the community.
I'll close this issue now if you're happy.

**Comment by spectrumcomputing** [comment]
Yes, please close. Thanks
