### ISSUE TITLE
Doesn't start when no 48k ROM @ "C:\Rom Images\ZX Spectrum 48K\image-0.rom"

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [stevehjohn/Zen#20]
Windows 10.

When the ROM is present in that location, it does start.

**Comment by stevehjohn** [comment]
Was this version 1.0.2?

Thanks,

Steve.

**Comment by stevehjohn** [comment]
Ah, I think I've fixed the problem. If you'd like to try v1.0.3, that should work now. Thanks for letting me know about the issue.

Steve.

**Comment by stevehjohn** [comment]
FFS. My bad again. I fixed the code but I think the release had the old binary. Just published another which I have tested and it should use a relative path to load the ROM.

Need to spend some time writing release scripts so I can't make mistakes like this again.

**Comment by stevehjohn** [comment]
Let me know when you are happy for me to close this issue.

Thanks,

Steve.

**Comment by TheStruggleForAntiSpaghetti** [comment]
Yeah, 1.0.4 works as expected 👍
